"""empty message

Revision ID: 010a084a6cdf
Revises: 88feb8f99248
Create Date: 2023-01-12 20:09:18.928521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010a084a6cdf'
down_revision = '88feb8f99248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
