"""Initial migration.

Revision ID: 0218cd3a4ded
Revises: 196421c00fe6
Create Date: 2023-01-11 19:13:29.310361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0218cd3a4ded'
down_revision = '196421c00fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=25),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    op.drop_table('address')
    # ### end Alembic commands ###
