"""empty message

Revision ID: 67952a2bf117
Revises: 0218cd3a4ded
Create Date: 2023-01-11 20:28:42.018149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67952a2bf117'
down_revision = '0218cd3a4ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
